version: "3.8"
services:
  mongo:
    image: mongo:6.0
    container_name: my-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27017:27017"
    volumes:
      - /Users/tuyennguyen/mongo-data:/data/db
    healthcheck: 
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })", "--quiet"] 
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017 
      - DB_USERNAME=root 
      - DB_PASSWORD=123456 
    ports:
      - 8080:8080
    expose:
      - 8080

    depends_on:
      mongo:
        condition: service_healthy

    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  
  nginx:
    image: nginx:1.23.3
      
        
    ports:
      - 3000:80
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    
    depends_on:
      backend:
        condition: service_healthy




  #- /Volumes/ExternalDriveName/mongo-data:/data/db
  # run command:  docker compose -p local-mogodb-backend up -d
  # du -hs /path/folder to see size of folder.


 